theme = "base16_transparent"

[editor]
rulers = [80, 120]
bufferline = 'multiple'
auto-pairs = false
soft-wrap = { enable = true }

[editor.file-picker]
hidden = false

[keys.normal]
space = { c = ':buffer-close', C = ':buffer-close!', l = ':toggle soft-wrap.enable', f = "file_picker_in_current_directory", F = "file_picker" }

