theme = "base16_transparent"

[editor]
rulers = [80, 120]
bufferline = 'multiple'
auto-pairs = false
soft-wrap = { enable = true }

[keys.normal]
space = { c = ':buffer-close', l = ':toggle soft-wrap.enable' }
